# Generated by Django 3.2.18 on 2023-06-20 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_image',
            field=models.ImageField(default='default/no_image.jpg', upload_to='user_images/'),
        ),
    ]
