version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    volumes:
    - ~/.pg/pg_data/user:/var/lib/postgresql/data
    env_file:
      - .env

  my_project:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: django
    depends_on:
      - postgres
    ports:
      - 8000:8000
    env_file:
      - .env

  redis:
    image: redis:7.2.3
    container_name: redis
    hostname: redis

  worker:
    build:
      context: .
    hostname: worker
    entrypoint: celery
    command: -A mysite worker --loglevel=info
    links:
      - redis
    depends_on:
      - redis
      - postgres
    env_file:
      - .env
