version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    volumes:
      - ./data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - 5432:5432

  redis:
    image: redis:7.2.3
    container_name: redis
    hostname: redis
    ports:
      - 6379:6379